/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManagerRole;

/**
 *
 * @author Shreya
 */

public class restaurantMainPageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RestaurantMainJPanel
     */
    public restaurantMainPageJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageEmployees = new javax.swing.JButton();
        btnConfirmBooking = new javax.swing.JButton();
        btnManageMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblsysadmin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 245, 235));
        setLayout(null);

        btnManageEmployees.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageEmployees.setText("MANAGE EMPLOYEES");
        add(btnManageEmployees);
        btnManageEmployees.setBounds(418, 282, 297, 30);

        btnConfirmBooking.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConfirmBooking.setText("CONFIRM BOOKINGS & ASSIGN ");
        btnConfirmBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmBookingActionPerformed(evt);
            }
        });
        add(btnConfirmBooking);
        btnConfirmBooking.setBounds(416, 349, 308, 30);

        btnManageMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageMenu.setText("MANAGE MENU");
        btnManageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMenuActionPerformed(evt);
            }
        });
        add(btnManageMenu);
        btnManageMenu.setBounds(418, 213, 297, 30);

        jPanel1.setBackground(new java.awt.Color(225, 225, 225));
        jPanel1.setLayout(null);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("BACK");
        jPanel1.add(btnBack);
        btnBack.setBounds(60, 30, 90, 40);

        lblsysadmin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblsysadmin.setText("RESTAURANT MANAGER");
        jPanel1.add(lblsysadmin);
        lblsysadmin.setBounds(410, 30, 470, 44);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1460, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmBookingActionPerformed

    private void btnManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmBooking;
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnManageMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblsysadmin;
    // End of variables declaration//GEN-END:variables
}
